// 幂等写入原生宿主清单与包装脚本。Chrome 拉起宿主时不带 PATH，包装脚本里写死 node 绝对路径。
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { NATIVE_HOST_NAME, extensionIds, semaChromeDir } from './protocol.js'

export function manifestDirs() {
  const home = os.homedir()
  switch (process.platform) {
    case 'darwin':
      return [path.join(home, 'Library', 'Application Support', 'Google', 'Chrome', 'NativeMessagingHosts')]
    case 'linux':
      return [path.join(home, '.config', 'google-chrome', 'NativeMessagingHosts')]
    default:
      throw new Error(`platform ${process.platform} is not supported yet`)
  }
}

export function ensureNativeHostInstalled() {
  const dir = semaChromeDir()
  fs.mkdirSync(dir, { recursive: true })

  const hostScript = fileURLToPath(new URL('../native-host.js', import.meta.url))
  const wrapperPath = path.join(dir, 'native-host.sh')
  const wrapper = [
    '#!/bin/sh',
    '# Sema browser control native host. Generated by bridge.js; edits are overwritten.',
    `exec ${shellQuote(process.execPath)} ${shellQuote(hostScript)} "$@"`,
    '',
  ].join('\n')
  let changed = writeIfChanged(wrapperPath, wrapper, 0o755)

  const manifest = `${JSON.stringify(
    {
      name: NATIVE_HOST_NAME,
      description: 'Sema browser control native host',
      path: wrapperPath,
      type: 'stdio',
      allowed_origins: extensionIds().map((id) => `chrome-extension://${id}/`),
    },
    null,
    2,
  )}\n`
  const manifestPaths = []
  for (const mdir of manifestDirs()) {
    fs.mkdirSync(mdir, { recursive: true })
    const p = path.join(mdir, `${NATIVE_HOST_NAME}.json`)
    changed = writeIfChanged(p, manifest, 0o644) || changed
    manifestPaths.push(p)
  }
  return { changed, wrapperPath, manifestPaths }
}

function writeIfChanged(file, content, mode) {
  let current = null
  try {
    current = fs.readFileSync(file, 'utf8')
  } catch {
    // 不存在
  }
  if (current === content) {
    fs.chmodSync(file, mode)
    return false
  }
  fs.writeFileSync(file, content, { mode })
  fs.chmodSync(file, mode)
  return true
}

function shellQuote(s) {
  return `'${String(s).replace(/'/g, `'\\''`)}'`
}
