# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sema.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'sema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nsema.proto\x12\x04sema\"P\n\rBridgeCommand\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\x12\x12\n\nsession_id\x18\x04 \x01(\t\"N\n\x0b\x42ridgeEvent\x12\r\n\x05\x65vent\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x0e\n\x06\x63md_id\x18\x03 \x01(\t\x12\x12\n\nsession_id\x18\x04 \x01(\t2C\n\nSemaBridge\x12\x35\n\x07\x43onnect\x12\x13.sema.BridgeCommand\x1a\x11.sema.BridgeEvent(\x01\x30\x01\x42\x42\n\x1a\x63om.sema.sdk.internal.grpcB\tSemaProtoP\x01\xaa\x02\x16Sema.Sdk.Internal.Grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\032com.sema.sdk.internal.grpcB\tSemaProtoP\001\252\002\026Sema.Sdk.Internal.Grpc'
  _globals['_BRIDGECOMMAND']._serialized_start=20
  _globals['_BRIDGECOMMAND']._serialized_end=100
  _globals['_BRIDGEEVENT']._serialized_start=102
  _globals['_BRIDGEEVENT']._serialized_end=180
  _globals['_SEMABRIDGE']._serialized_start=182
  _globals['_SEMABRIDGE']._serialized_end=249
# @@protoc_insertion_point(module_scope)
